name: Subir a S3 en cada push

on:
  push:
    branches:
      - main 

jobs:
  upload_to_s3:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Configurar AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Subir a S3
      run: aws s3 sync C:\Users\josperchi2\Documents\daw\Nueva%20carpeta\cv s3://joseperdomobucket
